apiVersion: v1
kind: Service
metadata: 
  namespace: s
  name: kubia-nodeport
spec: 
  type: NodePort
  ports: 
  - port: 81
    name: kubia-nodeport
    targetPort: 8080
    nodePort: 30081
  selector: 
    app: kubia