apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  namespace: s
  name: matrix-pvc
spec: 
  storageClassName: local-storage
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi