apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  namespace: s
  name: kubia
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: kubia
  template: 
    metadata: 
      labels: 
        app: kubia
    spec: 
      containers: 
      - image: luksa/kubia
        name: kubia
        ports: 
        - containerPort: 8080